/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 15.05.2026 08:25:34

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 6
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 12
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 3760;
#else
constexpr int kTensorArenaSize = 2736;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,650 } };
const TfArray<1, float> quant0_scale = { 1, { 0.029382830485701561, } };
const TfArray<1, int> quant0_zero = { 1, { 5 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 50, 13, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 50, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 25, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 25, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[4] = { 1, 1, 13, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data6[4] = { 1, 13, 1, 32, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data7[2] = { -1, 224, };
const TfArray<1, int> tensor_dimension7 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data8[3] = { -957, 688, 45, };
const TfArray<1, int> tensor_dimension8 = { 1, { 3 } };
const TfArray<1, float> quant8_scale = { 1, { 4.1082723328145221e-05, } };
const TfArray<1, int> quant8_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[3*224] = { 
  6, -45, -37, -109, 24, -29, -82, 16, 7, 24, -30, 1, 24, 19, -20, 14, -49, 11, 32, -52, -39, -3, 52, -9, -16, -78, -29, -50, 31, 26, -16, 34, 33, -68, -20, 45, 77, -40, -69, 37, -88, -17, -33, 23, 39, -3, -16, -15, -72, 29, 20, -14, -32, 3, -6, -47, -30, 80, -11, -53, -7, -27, 44, -5, 74, -58, -49, 34, 12, -27, -38, -7, -26, 30, -68, 67, -4, 0, 2, 8, 10, 45, 50, 17, 6, 6, -22, -59, 54, 8, -11, -27, -67, 5, 98, 15, 47, 27, -19, 60, -12, -22, 1, -39, -26, 36, -36, 28, -66, -40, 26, 10, -108, 50, 2, 24, -25, 36, -19, 79, -53, -38, -5, -5, 14, 19, 95, -1, 28, 14, 63, 48, 40, -23, 29, 39, -28, -15, -40, -27, -1, 16, 47, 56, -8, -1, 46, 62, 55, 0, 48, 14, 17, 30, -44, 18, 51, -54, -28, 23, 85, 9, 14, 48, 22, -35, -1, -6, 60, -18, -45, -22, -28, 15, 28, -52, -15, -3, 55, -10, -6, 65, 7, 44, 10, -8, -51, -65, 17, 51, -38, 66, -12, 37, 37, -34, 71, 63, -33, -18, 13, 24, 11, 10, -38, 49, -30, -40, -54, -13, 51, -20, 28, 19, -26, -19, -61, -17, -49, 1, 18, 76, 11, 27, 
  -73, -47, -20, 72, -53, 53, 9, -79, -21, 61, 23, 34, 98, 43, -28, 3, -21, -40, -52, -75, -9, -35, 5, -25, 60, 62, 48, -24, -24, -42, -8, -104, -94, 17, 20, -70, -126, 39, 2, -88, 47, -6, 31, -15, 0, 56, -58, -1, -1, -45, -54, -27, -5, -49, 20, 25, -16, -21, 63, 34, 28, 26, 6, -58, -27, -22, -6, 14, -81, 39, 65, -20, -53, -38, 3, 23, 19, 4, -28, -13, -2, -31, -44, -99, 8, -6, -13, 23, 8, -34, -49, -25, 13, -5, 26, -27, 30, -69, -12, -26, -57, -23, -17, -43, -12, -3, 68, -34, 21, 18, 51, -21, 28, -56, 9, -49, -4, -49, 1, -42, 13, -18, -3, -48, -73, -22, -45, -35, -64, -95, 21, 58, -70, -11, 19, -112, 4, -24, -31, -28, 1, 23, -10, 42, -26, -58, -10, 32, 18, -36, -12, 41, -27, -53, -30, 76, -47, -65, -16, -69, -38, 25, 37, 12, 1, -5, 50, -32, 36, 23, 54, -10, 83, 9, -30, 64, 12, -4, -14, -3, -22, -54, 26, -47, 75, 43, 68, 76, -1, 20, 15, 1, -41, -26, -12, -30, -31, 9, 51, 8, 23, -3, 5, -72, 0, 6, 59, -46, 3, -29, -76, 16, -22, -6, -19, -30, 45, -14, 45, -10, 14, 19, 56, 47, 
  -9, -35, -49, 47, -7, -19, 25, 24, 19, -79, -45, -19, -127, 16, 72, 27, 79, 48, -10, 51, 23, -12, 7, 36, -45, -23, -58, 85, 20, -38, -20, 69, 48, 80, 5, 55, -3, 46, -42, 7, 56, -42, 22, 19, -42, 6, 50, -29, 71, 13, 15, 27, 11, -9, -24, 36, 41, -17, -71, 50, -60, -21, -13, 4, -25, -5, 54, 14, -17, 22, 31, 40, 61, -53, -22, -35, 25, -14, -46, -47, -24, 4, -3, 11, 10, 41, -16, 54, 33, 40, -24, 52, 46, 13, -7, 74, 56, -29, -36, -39, -19, 24, -15, 31, 31, 1, 27, -89, -64, 41, 3, -61, 49, 50, -4, 26, 22, -43, 38, -28, -9, 54, 11, -1, -31, -20, 37, 23, -3, 47, 1, -52, -17, -18, -48, 25, 1, -28, -9, 56, 2, 41, -20, 7, -58, 45, 32, -91, 36, -32, 36, -36, -20, -25, -28, -45, -34, 19, 23, -80, 38, 25, -61, 37, 2, -55, 39, 2, -9, -21, -44, -89, -2, 1, 17, 0, 13, 16, 17, -56, -20, -5, 17, 36, -55, 6, 39, 13, 58, -54, 30, -52, 53, -74, -51, 30, 11, -49, -4, 36, -18, -23, -86, -3, 48, -34, 46, 46, -36, -41, -34, -28, -39, 28, -5, 10, -32, -32, 18, 22, -48, -21, -32, 2, 
};
const TfArray<2, int> tensor_dimension9 = { 2, { 3,224 } };
const TfArray<1, float> quant9_scale = { 1, { 0.0033525871112942696, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[32] = { 191, 491, -238, 839, -776, -586, -83, -88, -144, -760, -103, 11, 637, -1150, 103, 406, 694, 542, -431, 467, -1250, -603, -1731, 693, -646, -1459, 225, 890, -136, 155, -657, 786, };
const TfArray<1, int> tensor_dimension10 = { 1, { 32 } };
const TfArray<32, float> quant10_scale = { 32, { 5.082510324427858e-05, 3.6341803934192285e-05, 4.1945422708522528e-05, 4.7522004024358466e-05, 4.9346777814207599e-05, 4.0431601519230753e-05, 5.0964827096322551e-05, 4.9484751798445359e-05, 5.7635854318505153e-05, 4.8491645429749042e-05, 6.0192342061782256e-05, 4.8750949645182118e-05, 6.1699924117419869e-05, 3.8287140341708437e-05, 4.4424603402148932e-05, 5.0253176596015692e-05, 6.8438879679888487e-05, 5.9448149841045961e-05, 5.1180617447244003e-05, 5.18042579642497e-05, 3.8844558730488643e-05, 4.8567642807029188e-05, 4.1510957089485601e-05, 4.2918451072182506e-05, 5.8296627685194835e-05, 4.6804860176052898e-05, 5.7309953263029456e-05, 4.682624785345979e-05, 5.247725493973121e-05, 4.5423039409797639e-05, 6.7289241997059435e-05, 7.5815994932781905e-05, } };
const TfArray<32, int> quant10_zero = { 32, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[32*1*3*16] = { 
  /* [0][0][][] */ 70,85,-19,30,-85,-4,26,-65,20,-55,-103,46,93,-74,2,92, -21,100,80,26,-114,-115,88,-9,-3,-118,-127,-20,77,-102,47,-19, -22,-81,46,30,-113,-41,-14,79,75,-52,-98,-46,78,56,-16,-23, 
  /* [1][0][][] */ 66,-11,81,96,95,-127,82,112,-121,-90,48,33,-113,54,-26,49, 13,-108,50,-14,53,-86,114,70,72,57,33,16,-81,81,20,-92, -69,-67,16,92,-77,-74,-36,-96,-32,-78,33,39,-94,-13,77,46, 
  /* [2][0][][] */ -101,58,95,-60,-101,15,110,98,46,-96,6,-21,-2,72,72,35, 57,-52,86,23,-10,-9,65,-77,-63,68,85,-46,-54,-20,-13,-44, 106,55,-70,-25,-29,-99,-25,-11,-30,-34,-127,-115,13,59,47,86, 
  /* [3][0][][] */ 8,-66,15,68,-2,-63,49,-6,11,-50,-43,127,-7,-30,-46,-92, -8,115,125,69,-24,2,58,52,-20,-7,-27,68,-21,119,-112,-28, 19,-43,45,-90,12,36,105,27,-105,-105,-26,-95,-101,108,-43,10, 
  /* [4][0][][] */ 55,27,31,29,28,-126,127,-53,-97,-43,-42,47,75,-48,40,26, 67,29,-51,74,41,47,-4,9,-57,67,-67,-87,31,-20,66,34, -17,37,-43,-5,-29,-43,15,-76,-64,-85,41,-10,107,-26,5,-81, 
  /* [5][0][][] */ -52,12,22,-89,-2,15,48,37,-35,-54,-31,-68,1,102,-127,49, 24,12,-33,-93,20,44,21,78,7,-49,-112,-11,-70,127,60,-48, 22,-22,55,14,16,94,13,57,-32,61,37,-39,-116,-27,4,58, 
  /* [6][0][][] */ 56,-43,-7,-45,21,7,-43,44,29,16,19,69,-54,127,-71,-94, -28,-5,2,27,16,61,-76,37,42,-83,-15,122,-77,-11,30,33, 60,-25,56,-77,61,105,-56,18,-91,54,-6,-43,28,-70,-48,-25, 
  /* [7][0][][] */ 25,-68,-24,-42,-76,41,-24,-4,-48,6,114,59,-18,-7,-108,-76, 36,72,-30,-125,-127,20,64,-80,-94,-37,-34,63,116,-3,-87,-11, 81,112,-67,21,-99,-29,2,-77,-42,6,-52,52,2,54,99,45, 
  /* [8][0][][] */ 64,59,-53,56,-44,13,-7,75,-77,-15,-67,8,-32,-54,1,45, -68,-9,26,-19,55,21,-57,-14,16,-59,-90,-55,-84,-51,-18,-82, 47,51,10,17,-55,-51,-45,5,11,42,127,-26,-40,74,-1,-63, 
  /* [9][0][][] */ -80,49,8,-60,64,-37,127,25,74,45,-7,-45,92,20,-29,75, -58,5,29,43,33,72,1,-93,84,-81,27,-65,72,83,22,-32, -47,-79,59,88,19,-38,97,-58,-40,1,34,121,28,33,-7,23, 
  /* [10][0][][] */ -81,37,-70,-127,121,22,-14,45,-14,66,7,33,-38,72,-93,30, 38,-63,-33,30,22,89,-77,62,-35,32,-26,-55,6,65,56,11, -67,10,-7,-21,1,7,-16,-8,65,-7,20,-2,-58,-20,-57,-31, 
  /* [11][0][][] */ 33,56,-36,69,-85,-111,57,-92,79,25,-43,28,18,93,-127,55, 51,82,15,22,7,-71,122,-39,33,2,-107,12,-27,29,-92,-37, -57,-90,1,112,-5,76,-3,12,10,36,59,45,-2,85,1,-94, 
  /* [12][0][][] */ -16,7,-4,58,-40,9,-20,-53,44,-12,109,62,97,-24,45,-5, -74,65,44,-76,127,54,14,-52,-1,44,55,-57,-86,0,105,-10, -50,-1,-64,49,-59,32,46,-43,16,3,59,53,-10,-27,74,-47, 
  /* [13][0][][] */ -123,29,83,35,-14,91,43,54,75,-109,-27,-116,-103,-29,102,86, -19,-107,66,49,-75,-24,35,65,-112,90,-45,-108,8,-127,34,-52, -109,65,58,-25,-9,79,53,-103,59,89,-50,19,-11,-72,-61,72, 
  /* [14][0][][] */ -26,57,78,65,69,96,-28,-47,-36,-49,77,127,37,22,32,-29, -27,13,124,-13,-102,-103,-89,-35,55,-4,-59,-18,92,-57,-16,8, -39,53,107,1,-52,-41,-90,61,-42,-69,-72,-85,85,69,4,62, 
  /* [15][0][][] */ 20,43,83,-59,6,-36,20,-77,-47,63,105,12,-127,-26,-74,16, 38,45,13,-47,37,23,27,65,-99,-112,28,-19,38,14,39,64, -3,-74,-100,-99,-97,-10,-8,71,-112,-65,-43,-8,-88,-88,58,35, 
  /* [16][0][][] */ 25,-24,13,-127,2,66,-40,-7,-51,-42,-8,-2,12,5,52,-42, -43,9,-56,-30,-68,4,-24,46,-60,-47,67,44,-34,-20,-1,-66, 22,76,-2,-9,-33,36,-59,-42,-36,-9,-26,37,65,-35,-69,-25, 
  /* [17][0][][] */ -40,49,-42,76,-15,-78,-40,-25,-12,31,-95,-34,-34,-41,-10,45, 61,-8,46,78,-17,4,19,56,90,-10,-23,-7,-2,-87,-40,30, 43,49,-44,75,-75,-91,-127,72,-24,-80,-11,56,22,-42,-34,-58, 
  /* [18][0][][] */ 60,12,58,-53,-71,-91,93,-41,48,-51,-109,-39,54,-68,0,-4, 40,-98,-5,-15,-36,-23,48,65,1,-44,-68,15,127,40,-41,30, 39,-10,38,45,-58,-112,118,66,79,-21,-56,30,37,-75,-2,16, 
  /* [19][0][][] */ 45,-77,32,-34,27,47,69,-86,18,-76,54,31,0,93,-40,42, -18,36,-29,-52,-56,59,34,69,27,-77,-27,52,-21,-86,30,31, -74,19,24,127,0,-51,-124,70,-31,-54,-47,-46,-62,-90,-46,33, 
  /* [20][0][][] */ -118,62,-111,41,-7,-27,-58,8,-4,-7,-30,-96,34,23,75,26, -114,-104,82,-97,-51,-84,29,84,-105,48,16,-68,17,9,-77,-61, 35,66,-77,-127,-84,-87,-1,-46,41,-27,-62,14,-34,33,-35,31, 
  /* [21][0][][] */ -80,-33,-16,112,-87,35,-85,-4,-52,15,-56,68,-23,-80,-101,-57, -59,-45,57,-27,-29,-40,67,59,-28,-44,-11,27,-20,-86,82,-60, -127,24,73,-46,-104,-4,16,50,69,-45,-66,-109,-40,-39,-77,-3, 
  /* [22][0][][] */ -94,0,26,-20,-85,-6,44,40,-19,-69,-20,-103,-127,-88,-104,-76, 80,39,66,-77,43,-87,-74,-53,26,-21,-70,-51,58,-124,1,-98, 75,-11,24,-49,-115,-124,-17,32,-66,36,6,29,7,-4,-78,-24, 
  /* [23][0][][] */ -23,-102,-45,90,-33,-6,31,-16,34,-38,87,16,-44,39,-108,-3, 52,30,100,-122,-45,-51,18,112,-4,-127,-11,25,-22,56,31,82, -6,-44,70,8,-87,93,-34,-23,39,-31,-63,40,60,-85,-34,96, 
  /* [24][0][][] */ -68,0,-49,-73,54,95,-14,65,38,20,70,4,75,126,0,26, 20,23,-9,52,74,51,-46,11,-93,14,-24,11,-105,14,16,23, -90,-70,30,14,-36,-39,16,-70,58,-41,-73,65,31,-127,-49,-73, 
  /* [25][0][][] */ 6,21,9,30,-111,-105,-4,-18,9,-67,-68,-7,-70,-52,8,-69, 40,14,-24,77,89,127,9,-100,65,7,-127,-4,-19,22,4,85, 47,-53,8,-4,-33,-22,30,-1,-78,56,12,-41,-32,15,76,-1, 
  /* [26][0][][] */ 60,12,30,27,32,35,-49,-13,73,105,70,49,-83,82,45,25, 25,54,54,-37,48,78,32,-8,-48,-31,-43,10,-127,-31,23,-35, 22,-45,25,-10,-21,-88,9,-44,-62,-56,58,110,3,-26,-31,59, 
  /* [27][0][][] */ 43,80,86,-72,5,-23,-1,-79,-45,-20,-112,-34,-69,127,-54,-4, 11,-44,77,-50,-66,88,-55,-30,0,-120,-127,-84,-35,-41,-66,-16, 76,-6,7,109,-12,113,-12,117,-41,-109,127,-18,31,-112,-55,72, 
  /* [28][0][][] */ -34,-84,11,65,-38,-75,13,61,-26,-74,17,0,-127,76,-23,3, 93,11,-40,61,-13,18,33,-63,-21,-76,42,-54,-79,-27,66,-88, 77,-13,52,-79,-53,14,110,50,68,-27,22,9,124,-26,92,12, 
  /* [29][0][][] */ 15,78,-100,-59,64,-91,-20,63,-95,-54,56,-94,42,10,-58,-90, -70,-44,56,68,44,-93,6,27,82,41,20,-88,59,-45,38,-100, -103,-88,-62,34,34,56,56,-76,5,-91,78,55,32,-26,127,-43, 
  /* [30][0][][] */ 25,32,-55,45,13,-30,-22,-78,1,7,-13,-52,40,32,69,-20, -47,48,15,10,19,-41,46,-76,45,-42,-74,9,-38,35,-27,13, -9,26,-25,35,-8,31,-43,25,75,-8,55,127,51,37,-60,8, 
  /* [31][0][][] */ -13,21,20,-51,-74,-34,56,-41,6,-117,-17,-75,-73,-45,-7,-63, -11,14,8,-46,-28,2,9,24,-54,-64,33,55,73,-5,-18,-24, 71,-47,33,29,-10,-48,44,38,-46,-29,49,9,127,-31,-11,-19, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 32,1,3,16 } };
const TfArray<32, float> quant11_scale = { 32, { 0.0024846771266311407, 0.0017766348319128156, 0.0020505778957158327, 0.002323199063539505, 0.0024124064948409796, 0.0019765719771385193, 0.0024915076792240143, 0.0024191515985876322, 0.0028176328632980585, 0.0023706017527729273, 0.002942611463367939, 0.0023832782171666622, 0.0030163123738020658, 0.0018717361381277442, 0.0021717769559472799, 0.0024567174259573221, 0.0033457584213465452, 0.0029062302783131599, 0.0025020570028573275, 0.0025325447786599398, 0.0018989864038303494, 0.0023743170313537121, 0.0020293381530791521, 0.0020981461275368929, 0.00284993601962924, 0.0022881401237100363, 0.0028017007280141115, 0.0022891857661306858, 0.0025654453784227371, 0.0022205873392522335, 0.0032895561307668686, 0.0037064019124954939, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data12[16] = { -33, 340, -412, 466, 1516, 413, -647, -409, -258, 182, 753, 843, 398, 754, -572, -596, };
const TfArray<1, int> tensor_dimension12 = { 1, { 16 } };
const TfArray<16, float> quant12_scale = { 16, { 7.5314157584216446e-05, 6.5384287154302001e-05, 5.6384647905360907e-05, 6.4468746131751686e-05, 6.8984816607553512e-05, 8.0683552369009703e-05, 6.7368047893978655e-05, 8.8448839960619807e-05, 6.6438944486435503e-05, 7.0708236307837069e-05, 7.9168989032041281e-05, 8.7648120825178921e-05, 7.0154150307644159e-05, 7.0770969614386559e-05, 6.918268627487123e-05, 5.3318759455578402e-05, } };
const TfArray<16, int> quant12_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant12 = { (TfLiteFloatArray*)&quant12_scale, (TfLiteIntArray*)&quant12_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data13[16*1*3*8] = { 
  /* [0][0][][] */ 44,33,53,80,-53,-25,-4,50, 22,19,-24,-2,-74,-3,84,-70, 66,99,28,58,-127,-51,56,40, 
  /* [1][0][][] */ -51,81,-39,100,-45,-123,-9,31, -35,-23,-79,20,82,107,72,95, 112,10,50,-127,-42,-52,1,-50, 
  /* [2][0][][] */ -36,7,-79,-20,15,-54,15,48, 115,-29,55,41,67,-127,1,89, -86,10,17,-105,-65,55,84,-30, 
  /* [3][0][][] */ 74,-111,95,-52,127,-6,-78,27, 13,-123,-24,79,11,-80,-44,12, -56,-9,-20,-8,90,-46,123,62, 
  /* [4][0][][] */ -51,-15,-79,-16,-87,-20,-2,75, -117,-20,-48,-60,-10,120,29,-5, 69,91,120,-80,-68,127,-38,64, 
  /* [5][0][][] */ -74,72,88,43,6,-65,-50,76, -108,90,4,-47,73,110,-63,-26, -66,127,83,32,-32,59,-73,78, 
  /* [6][0][][] */ 104,25,9,66,-120,-73,-36,36, 70,-78,-8,-89,-33,-44,-26,94, 7,-78,-103,42,5,-15,-127,-91, 
  /* [7][0][][] */ -13,67,-6,-127,-63,92,63,22, 18,58,52,55,44,56,33,44, -11,-6,-50,-35,55,31,85,13, 
  /* [8][0][][] */ 49,-118,61,82,14,-33,81,38, -34,-77,-47,59,110,-68,-127,103, -22,-62,88,67,27,40,-50,-19, 
  /* [9][0][][] */ 30,-31,86,80,-43,107,30,44, -43,-35,19,-40,-9,114,-77,13, -25,-96,-29,127,-47,99,-61,92, 
  /* [10][0][][] */ -103,-37,-18,55,36,-6,58,-20, -127,-66,-18,-7,-18,-95,-100,34, -22,40,-62,63,-103,65,-12,109, 
  /* [11][0][][] */ -51,27,-65,92,69,11,-23,-13, -45,-66,10,35,82,-127,-16,71, -20,-3,-71,29,-38,-104,-48,0, 
  /* [12][0][][] */ -19,97,-115,127,-69,-55,98,-30, 113,-12,-102,31,-84,46,-122,-46, 99,58,27,90,36,-81,-98,50, 
  /* [13][0][][] */ 20,-15,-43,-38,-60,94,-62,-2, 68,12,-42,-36,-71,-58,-58,-61, -45,21,127,-34,121,-92,-68,89, 
  /* [14][0][][] */ 36,-4,73,-71,22,73,31,-52, -37,86,93,-2,-20,-9,46,-103, 76,-124,10,73,-28,-127,-25,-86, 
  /* [15][0][][] */ 47,42,-51,-86,45,-66,-76,81, -44,-62,52,-15,8,-110,25,77, -100,-127,42,-110,-126,-24,5,67, 
};
const TfArray<4, int> tensor_dimension13 = { 4, { 16,1,3,8 } };
const TfArray<16, float> quant13_scale = { 16, { 0.0030320598743855953, 0.0026322950143367052, 0.0022699800319969654, 0.0025954362936317921, 0.0027772479224950075, 0.0032482254318892956, 0.00271215895190835, 0.0035608469042927027, 0.0026747542433440685, 0.0028466309886425734, 0.0031872510444372892, 0.0035286108031868935, 0.0028243241831660271, 0.0028491565026342869, 0.002785213990136981, 0.0021465509198606014, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant12_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data14[8] = { -875, 317, -1162, 862, 783, 165, -632, 238, };
const TfArray<1, int> tensor_dimension14 = { 1, { 8 } };
const TfArray<8, float> quant14_scale = { 8, { 0.0001019541741698049, 0.00012335657083895057, 9.3611371994484216e-05, 9.7671705589164048e-05, 9.5064264314714819e-05, 0.00010955372272292152, 9.9608674645423889e-05, 7.7692071499768645e-05, } };
const TfArray<8, int> quant14_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant14 = { (TfLiteFloatArray*)&quant14_scale, (TfLiteIntArray*)&quant14_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data15[8*1*3*13] = { 
  /* [0][0][][] */ -25,-1,19,23,-70,-19,66,-72,-36,35,37,-64,92, -89,-127,47,2,-6,-2,-30,-23,32,94,50,-7,8, -28,-127,43,-28,-50,31,34,-89,42,3,19,-62,76, 
  /* [1][0][][] */ -91,-93,-43,49,-61,25,-50,127,-22,-32,-40,-6,67, -71,46,24,-56,-10,42,88,75,-34,8,32,21,-37, -80,-36,-19,26,37,-97,6,12,13,47,-72,-79,14, 
  /* [2][0][][] */ 67,113,-16,-37,-83,-127,17,72,-53,53,48,-71,30, -104,-16,100,50,-116,-2,34,95,-15,5,21,33,-37, -75,-61,-4,-127,-96,40,-42,64,56,-36,67,-118,-2, 
  /* [3][0][][] */ -86,-21,6,-81,54,-27,25,17,81,-111,-18,-113,-67, 8,3,15,127,31,39,25,58,83,70,103,40,81, 56,-63,90,39,42,53,52,47,49,32,-46,-5,-121, 
  /* [4][0][][] */ 81,-40,-20,99,-52,-8,-11,73,-12,-4,-79,89,72, 60,-11,63,-52,-37,-37,-55,-30,-77,-95,-14,-101,-43, -20,77,50,-40,-69,28,-61,-95,30,-84,-29,127,-30, 
  /* [5][0][][] */ 17,3,12,34,39,12,-27,2,-5,34,-84,73,8, 87,-68,38,-56,8,20,121,-26,-36,94,-97,-37,-72, 48,44,-20,95,-127,87,54,-38,47,48,-2,-30,91, 
  /* [6][0][][] */ 100,108,-6,0,-35,-7,-30,-66,-127,-116,-67,15,-60, 29,15,-26,-42,67,52,37,-9,30,-4,39,-26,26, 124,45,33,-49,-49,-29,77,-48,-50,13,-69,38,-30, 
  /* [7][0][][] */ 90,6,82,51,58,39,-99,49,-8,-48,118,-100,74, -123,-37,28,-13,127,-19,-19,-14,88,-83,-27,76,-8, -58,81,115,109,-53,-61,105,86,-46,-58,46,-54,50, 
};
const TfArray<4, int> tensor_dimension15 = { 4, { 8,1,3,13 } };
const TfArray<8, float> quant15_scale = { 8, { 0.0034698555245995522, 0.004198253620415926, 0.0031859208829700947, 0.0033241081982851028, 0.0032353678252547979, 0.0037284945137798786, 0.0033900300040841103, 0.0026441316585987806, } };
const TfLiteAffineQuantization quant15 = { (TfLiteFloatArray*)&quant15_scale, (TfLiteIntArray*)&g0::quant14_zero, 0 };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,50,13 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,50,8 } };
const TfArray<1, float> quant17_scale = { 1, { 0.024839270859956741, } };
const TfArray<1, int> quant17_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&quant17_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,50,1,8 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,25,1,8 } };
const TfArray<4, int> tensor_dimension20 = { 4, { 1,1,25,8 } };
const TfArray<4, int> tensor_dimension21 = { 4, { 1,1,25,16 } };
const TfArray<1, float> quant21_scale = { 1, { 0.020455416291952133, } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&g0::quant17_zero, 0 };
const TfArray<4, int> tensor_dimension22 = { 4, { 1,25,1,16 } };
const TfArray<4, int> tensor_dimension23 = { 4, { 1,13,1,16 } };
const TfArray<4, int> tensor_dimension24 = { 4, { 1,1,13,16 } };
const TfArray<4, int> tensor_dimension25 = { 4, { 1,1,13,32 } };
const TfArray<1, float> quant25_scale = { 1, { 0.012254036031663418, } };
const TfLiteAffineQuantization quant25 = { (TfLiteFloatArray*)&quant25_scale, (TfLiteIntArray*)&g0::quant17_zero, 0 };
const TfArray<4, int> tensor_dimension26 = { 4, { 1,13,1,32 } };
const TfArray<4, int> tensor_dimension27 = { 4, { 1,7,1,32 } };
const TfArray<2, int> tensor_dimension28 = { 2, { 1,224 } };
const TfArray<2, int> tensor_dimension29 = { 2, { 1,3 } };
const TfArray<1, float> quant29_scale = { 1, { 0.0439017154276371, } };
const TfArray<1, int> quant29_zero = { 1, { 24 } };
const TfLiteAffineQuantization quant29 = { (TfLiteFloatArray*)&quant29_scale, (TfLiteIntArray*)&quant29_zero, 0 };
const TfArray<1, float> quant30_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant30 = { (TfLiteFloatArray*)&quant30_scale, (TfLiteIntArray*)&g0::quant17_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 16 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 16,15,14 } };
const TfArray<1, int> outputs1 = { 1, { 17 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 17,2 } };
const TfArray<1, int> outputs2 = { 1, { 18 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 18 } };
const TfArray<1, int> outputs3 = { 1, { 19 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 19,3 } };
const TfArray<1, int> outputs4 = { 1, { 20 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 20,13,12 } };
const TfArray<1, int> outputs5 = { 1, { 21 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 21,4 } };
const TfArray<1, int> outputs6 = { 1, { 22 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 22 } };
const TfArray<1, int> outputs7 = { 1, { 23 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 23,5 } };
const TfArray<1, int> outputs8 = { 1, { 24 } };
const TfLiteConvParams opdata9 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs9 = { 3, { 24,11,10 } };
const TfArray<1, int> outputs9 = { 1, { 25 } };
const TfLiteReshapeParams opdata10 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs10 = { 2, { 25,6 } };
const TfArray<1, int> outputs10 = { 1, { 26 } };
const TfLitePoolParams opdata11 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs11 = { 1, { 26 } };
const TfArray<1, int> outputs11 = { 1, { 27 } };
const TfLiteReshapeParams opdata12 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs12 = { 2, { 27,7 } };
const TfArray<1, int> outputs12 = { 1, { 28 } };
const TfLiteFullyConnectedParams opdata13 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs13 = { 3, { 28,9,8 } };
const TfArray<1, int> outputs13 = { 1, { 29 } };
const TfLiteSoftmaxParams opdata14 = { 1 };
const TfArray<1, int> inputs14 = { 1, { 29 } };
const TfArray<1, int> outputs14 = { 1, { 30 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 656), (TfLiteIntArray*)&g0::tensor_dimension0, 650, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 672, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 128, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 1536, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data12, (TfLiteIntArray*)&g0::tensor_dimension12, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data13, (TfLiteIntArray*)&g0::tensor_dimension13, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data14, (TfLiteIntArray*)&g0::tensor_dimension14, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant14))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data15, (TfLiteIntArray*)&g0::tensor_dimension15, 312, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant15))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 650, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 656), (TfLiteIntArray*)&g0::tensor_dimension17, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension19, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension21, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension22, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension23, 208, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension24, 208, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 416), (TfLiteIntArray*)&g0::tensor_dimension25, 416, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant25))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension26, 416, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant25))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 416), (TfLiteIntArray*)&g0::tensor_dimension27, 224, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant25))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension28, 224, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant25))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 224), (TfLiteIntArray*)&g0::tensor_dimension29, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant29))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension29, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant30))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[15] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs11, (TfLiteIntArray*)&g0::outputs11, (TfLiteIntArray*)&g0::inputs11, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata11)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs12, (TfLiteIntArray*)&g0::outputs12, (TfLiteIntArray*)&g0::inputs12, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata12)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs13, (TfLiteIntArray*)&g0::outputs13, (TfLiteIntArray*)&g0::inputs13, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata13)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs14, (TfLiteIntArray*)&g0::outputs14, (TfLiteIntArray*)&g0::inputs14, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata14)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[15] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs11, (TfLiteIntArray*)&g0::outputs11, (TfLiteIntArray*)&g0::inputs11, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata11)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs12, (TfLiteIntArray*)&g0::outputs12, (TfLiteIntArray*)&g0::inputs12, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata12)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs13, (TfLiteIntArray*)&g0::outputs13, (TfLiteIntArray*)&g0::inputs13, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata13)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs14, (TfLiteIntArray*)&g0::outputs14, (TfLiteIntArray*)&g0::inputs14, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata14)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 31, };
const size_t tflNodes_subgraph_index[] = {0, 15, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  30, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_985318_52_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 31;
  for (size_t i = 0; i < 31; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_985318_52_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_985318_52_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_985318_52_invoke() {
  for (size_t i = 0; i < 15; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_985318_52_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
