#!/usr/bin/env python3
"""
gen_thumb_ref.py — embed the golden-reference JPEG as a C byte array.

Usage (run from the project root):
    python tools/gen_thumb_ref.py

Input:
    assets/test_input/youtube_ref_mqdefault_320x180.jpg

Output (overwrites):
    CM7/Core/Src/thumb_ref_jpeg.c

After running, rebuild the IAR project. Stage 1 RTT logs should then show:
    [THUMB][DEC][OK] ptr=0x...  len=<real size>
    [THUMB][DEC][DATA] head= FF D8 FF ...
    [THUMB][DEC][DATA] tail= ... FF D9
    [THUMB][DEC][OK] jpeg signature valid — Stage 1 complete
"""

import os
import sys

SRC_REL = os.path.join("assets", "test_input",
                        "youtube_ref_mqdefault_320x180.jpg")
DST_REL = os.path.join("CM7", "Core", "Src", "thumb_ref_jpeg.c")

# Resolve paths relative to this script's parent (project root)
script_dir  = os.path.dirname(os.path.abspath(__file__))
project_dir = os.path.dirname(script_dir)
src_path    = os.path.join(project_dir, SRC_REL)
dst_path    = os.path.join(project_dir, DST_REL)

if not os.path.isfile(src_path):
    print(f"ERROR: source not found:\n  {src_path}")
    print("Place youtube_ref_mqdefault_320x180.jpg in assets/test_input/ first.")
    sys.exit(1)

with open(src_path, "rb") as f:
    data = f.read()

size = len(data)

# Sanity-check JPEG markers
if len(data) < 4 or data[0] != 0xFF or data[1] != 0xD8:
    print("ERROR: file does not start with JPEG SOI marker (FF D8)")
    sys.exit(1)
if data[-2] != 0xFF or data[-1] != 0xD9:
    print("WARNING: file does not end with JPEG EOI marker (FF D9) — "
          "the file may be truncated")

print(f"Source : {src_path}")
print(f"Size   : {size} bytes ({size/1024:.1f} KB)")
print(f"Head   : {' '.join(f'{b:02X}' for b in data[:8])}")
print(f"Tail   : {' '.join(f'{b:02X}' for b in data[-8:])}")

with open(dst_path, "w", newline="\n") as f:
    f.write("/* AUTO-GENERATED by tools/gen_thumb_ref.py — do not edit manually.\n")
    f.write(f" * Source : {SRC_REL}\n")
    f.write(f" * Size   : {size} bytes ({size/1024:.1f} KB)\n")
    f.write(f" * Head   : {' '.join(f'{b:02X}' for b in data[:8])}\n")
    f.write(f" * Tail   : {' '.join(f'{b:02X}' for b in data[-8:])}\n")
    f.write(" * Re-run this script after replacing the source JPEG. */\n")
    f.write("\n")
    f.write('#include "thumb_ref_jpeg.h"\n')
    f.write("\n")
    f.write("const uint8_t g_thumb_ref_jpeg[] = {\n")
    for i, b in enumerate(data):
        if i % 16 == 0:
            f.write("    ")
        f.write(f"0x{b:02X},")
        if i % 16 == 15 or i == size - 1:
            f.write("\n")
        else:
            f.write(" ")
    f.write("};\n")
    f.write("\n")
    f.write("const uint32_t g_thumb_ref_jpeg_len = (uint32_t)sizeof(g_thumb_ref_jpeg);\n")

print(f"Written: {dst_path}")
print("Rebuild the IAR project and flash to see Stage 1 pass.")
